### ISSUE TITLE
"Need at least one mount" when trying to vendor fontawesome

### ISSUE THREAD

**Issue by peacememories** [hugomods/icons#303]
Hi, and thanks for creating this hugo module :)

I've run into a problem when using github.com/hugomods/icons/vendors/font-awesome as a module. My build system ([nix](https://nixos.org/)) does not allow downloading anything during a build, so the dependencies need to be vendored. But when I use `hugo mod vendor`, I get the following error:

```
Error: cannot vendor module "github.com/hugomods/font-awesome", need at least one mount
```

This also happens when I manually put this in my `hugo.toml`

```toml
[module]
[[module.imports]]
    path = 'github.com/hugomods/font-awesome'
[[module.imports.mounts]]
    source = "svg/brands"
    target = "assets/icons/font-awesome-brands"
[[module.imports.mounts]]
    source = "svg/solid"
    target = "assets/icons/font-awesome-solid"
[[module.imports]]
    path = 'github.com/hugomods/icons'
```

I also found that this seems to be a more common problem with Hugo/Go (see https://github.com/gohugoio/hugo/issues/10123)

I'm unsure how to work around this since I am not very familiar with Go module internals. Is there a way to create a mount that makes `hugo mod vendor` happy?
