### ISSUE TITLE
How to reference Tabler - type icons in theme - start? Thank you.

### ISSUE THREAD

**Issue by lss53** [hugomods/icons#461]
![](https://github.com/user-attachments/assets/19ee514f-32ba-428a-acb9-11610e16933b)
In theme - start, How to quote? Thank you.
```
  - name: Test
    parent: test
    url: https://bilibili.com
    weight: 1
    params:
      icon:
        vendor: ?
        name: ?
```
